In [1]:
import TwitterSentiments as TS
import numpy as np
import importlib
importlib.reload(TS)
import json
import pandas as pd

In [ ]:
X,y = TS.feature_gen('obama')

In [ ]:
X = np.array(X)
np.savetxt('/tmp/test.txt', X)

In [ ]:
np.savetxt('/tmp/y.txt', y)

In [ ]:
with open('/tmp/y.txt','r') as yD:
    y = yD.read().split("\n")
    
Y = [np.float(y[i]) for i in range(len(y)-1)]

In [ ]:
np.float('-1.000000000000000000e+00')

In [ ]:
Y

In [8]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,roc_auc_score,roc_curve

In [10]:
from sklearn.model_selection import cross_val_predict, cross_val_score

In [3]:
X, y = TS.feature_gen('obama')

In [19]:
clf = TS.getClf('ada_boost')

In [20]:
predicted = cross_val_predict(clf, X, y, cv=10)

In [23]:
print(accuracy_score(y, predicted))
print(precision_score(y, predicted, average=None))
print(recall_score(y, predicted, average=None))
print(f1_score(y, predicted, average=None))
clf.p

0.490210430009
[ 0.48745215  0.44784876  0.53544304]
[ 0.596875    0.36291601  0.51210654]
[ 0.53664247  0.40093376  0.52351485]


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [22]:
cross_val_score(clf, X, y, cv=10)

array([ 0.46350365,  0.38321168,  0.52468007,  0.52197802,  0.52564103,
        0.54395604,  0.55494505,  0.43040293,  0.48717949,  0.46703297])

In [69]:
with open("../data/romneyTweets.json","r") as candidJson:
        candid_rec = json.load(candidJson) 

In [94]:
all_attribs = TS.genVocab(candid_rec)
df = TS.gen_BagOfWords(candid_rec)

TypeError: gen_BagOfWords() missing 1 required positional argument: 'allAttribs'

In [103]:
df = TS.gen_BagOfWords(candid_rec, all_attribs)

In [104]:
df.isnull().any().any()

False

In [91]:
def gen_BagOfWords(recds,allAttribs,header='Anootated tweet'):
    data = []
    for rec in recds:
        if len(rec[header]) > 0:
            ftrVector = dict.fromkeys(allAttribs,0)
            i = len(ftrVector) +1 
            for word in rec[header]:
                if word != '' and word in allAttribs:
                    ftrVector[word] = ftrVector.get(word,0) + 1
                    ftrVector['class'] = rec['Class']
            j = len(ftrVector)
            if i != j:
                print(rec)
                print("lavde")
            data.append(ftrVector)
    
    return data

In [105]:
X, y = TS.tfIDfVectorizer(df)

In [106]:
df['class']

KeyError: 'class'

In [107]:
df

08act  0o  1000th  10k  1130am  11oclock  11th  12m  12mm  13million  \
0         0   0       0    0       0         0     0    0     0          0   
1         0   0       0    0       0         0     0    0     0          0   
2         0   0       0    0       0         0     0    0     0          0   
3         0   0       0    0       0         0     0    0     0          0   
4         0   0       0    0       0         0     0    0     0          0   
5         0   0       0    0       0         0     0    0     0          0   
6         0   0       0    0       0         0     0    0     0          0   
7         0   0       0    0       0         0     0    0     0          0   
8         0   0       0    0       0         0     0    0     0          0   
9         0   0       0    0       0         0     0    0     0          0   
10        0   0       0    0       0         0     0    0     0          0   
11        0   0       0    0       0         0     0    0     0          0   
12        0   0       0    0       0         0     0    0     0          0   
13        0   0       0    0       0         0     0    0     0          0   
14        0   0       0    0       0         0     0    0     0          0   
15        0   0       0    0       0         0     0    0     0          0   
16        0   0       0    0       0         0     0    0     0          0   
17        0   0       0    0       0         0     0    0     0          0   
18        0   0       0    0       0         0     0    0     0          0   
19        0   0       0    0       0         0     0    0     0          0   
20        0   0       0    0       0         0     0    0     0          0   
21        0   0       0    0       0         0     0    0     0          0   
22        0   0       0    0       0         0     0    0     0          0   
23        0   0       0    0       0         0     0    0     0          0   
24        0   0       0    0       0         0     0    0     0          0   
25        0   0       0    0       0         0     0    0     0          0   
26        0   0       0    0       0         0     0    0     0          0   
27        0   0       0    0       0         0     0    0     0          0   
28        0   0       0    0       0         0     0    0     0          0   
29        0   0       0    0       0         0     0    0     0          0   
...     ...  ..     ...  ...     ...       ...   ...  ...   ...        ...   
5616      0   0       0    0       0         0     0    0     0          0   
5617      0   0       0    0       0         0     0    0     0          0   
5618      0   0       0    0       0         0     0    0     0          0   
5619      0   0       0    0       0         0     0    0     0          0   
5620      0   0       0    0       0         0     0    0     0          0   
5621      0   0       0    0       0         0     0    0     0          0   
5622      0   0       0    0       0         0     0    0     0          0   
5623      0   0       0    0       0         0     0    0     0          0   
5624      0   0       0    0       0         0     0    0     0          0   
5625      0   0       0    0       0         0     0    0     0          0   
5626      0   0       0    0       0         0     0    0     0          0   
5627      0   0       0    0       0         0     0    0     0          0   
5628      0   0       0    0       0         0     0    0     0          0   
5629      0   0       0    0       0         0     0    0     0          0   
5630      0   0       0    0       0         0     0    0     0          0   
5631      0   0       0    0       0         0     0    0     0          0   
5632      0   0       0    0       0         0     0    0     0          0   
5633      0   0       0    0       0         0     0    0     0          0   
5634      0   0       0    0       0         0     0    0     0          0   
5635      0   0       0    0

In [114]:
var1 = ["obama", "romney"]
var2 = ['bayes', 'logisitic', 'dtree', 'rf', 'svm', 'ada_boost']
for v1 in var1:
    for v2 in var2:
        print('/tmp/%s_%s.dat' %(v1,v2))

/tmp/obama_bayes.dat
/tmp/obama_logisitic.dat
/tmp/obama_dtree.dat
/tmp/obama_rf.dat
/tmp/obama_svm.dat
/tmp/obama_ada_boost.dat
/tmp/romney_bayes.dat
/tmp/romney_logisitic.dat
/tmp/romney_dtree.dat
/tmp/romney_rf.dat
/tmp/romney_svm.dat
/tmp/romney_ada_boost.dat


In [10]:
df_obama = pd.read_excel("../data/testing-Obama-Romney-tweets.xlsx",sheetname='Obama').dropna(how='any')

In [11]:
df_obama

Anootated tweet Class
0     I'd like to punch <e>Obama</e> in the face. So...    -1
1     <e>Obama</e> wants to tax foreign earnings. Th...    -1
2     <e>Obama</e> has to maintain his professionali...     1
3     I hate <e>Obama</e> with a BURNING PASSION #de...    -1
4     I don't like<e>Obama</e> because his stupid <a...    -1
5     The only thing I don't like about <e>Obama</e>...    -1
6     <e>Obama</e>snuck the 47% in when<e>Romney </e...     2
7     The people who vote for<e>Obama</e> dont reali...    -1
8     It's difficult to give <e>Obama</e> a grade wh...    -1
9     cspanwj <e>Obama</e> LOST IN BOTH STYLE AND SU...    -1
10    <e>Obama</e><a> lied about his rosé garden cla...    -1
11    <e>Obama</e> went into the debate swinging and...     1
12    <e>Obama</e> came across as bitter, condescend...    -1
13                 I literally can't stand<e>Obama</e>.    -1
14    Can anyone who is a <e>Obama</e> supporter giv...     0
15    I loved when <e>Romney </e>kept asking <e>Obam...     2
16    The choice is clear: morning in America or thi...    -1
17    How does <e>Obama</e> keep a straight face wit...    -1
18    <e>Obama</e>: "I'm the president and I'm alway...    -1
19    Free Market economies are ran by the people an...     0
20    POW! BAM! “@secupp: <e>Romney </e>just crushed...     2
21    Ditto. I started @247LS 4 years ago. RT @bmorr...     1
22    Look at <e>Obama</e>'s record hell ya <e>Mitt ...     2
23    <e>Obama</e>'s problem - good rhetoric, but ba...    -1
24    I love that #<e>romney </e>can call out and as...     2
25    I can't believe people are still believing<e>O...    -1
26    <e>Obama</e>'s giant <a>ears</a> probably wish...    -1
27    #debates  Overwhelming theme of debate is <e>O...     2
28    <e>Obama</e>'s deported a record number of peo...    -1
29    <e>Obama</e>'s administration enabled the murd...    -1
...                                                 ...   ...
2371   @vickikellar Candy cutting off <e>Romney</e> ...     2
2372   Seeing and hearing <e>Obama</e> was pretty co...     1
2373   #SupremeCourt Agrees To Hear Case On #Federal...     0
2374   <e>Obama</e>  <e>Romney</e> Reprise Their Gre...     2
2375   Again  <e>Obama</e> did NOT call Benghazi an ...    -1
2376   There's an anti <e>Obama</e> thing going on o...     1
2377   Denied on phish lotto x3. Email right after w...     0
2378   5 Twitter Lessons From the <e>Obama</e> and <...     2
2379   Sharpton's guest said: The right-wing doesn't...     2
2380   Thought there was an invasion going on outsid...     0
2381   "@RickWarren: Another Christian University(ET...     0
2382   <e>Obama</e> cleared all the troops out of Ir...    -1
2383   "@SheWantThaD: If <e>Obama</e> Loses   I Say ...     1
2384   #Rommunism = <e>Romney</e>'s <a>Economic Plan...     2
2385   Obama-rama! Barack deserves a second term. He...     1
2386   @IngrahamAngle Of course O did say "act of te...    -1
2387   People need to listen to <e>Obama</e>   not l...     1
2388   ‰ÛÏIt is highly offensive that the <e>Obama</...    -1
2389   KEEP THE GOOD NEWS COMING! Obama's lead over ...    -1
2390   ‹ÛNews‹ÛÔ Obama  <e>Romney</e> seek support ...     2
2391   #Obama said <a>gas prices</a> low under Bush ...    -1
2392    41199 PM 0.292361111111111 Gender gap contin...     0
2393   This election may come down to people who lov...     1
2394   <e>Obama<e><e>Romney</e>                     ...     2
2395   @jtLOL Mitt puts them in binders; <e>Obama</e...     2
2396   ‰ÑÈ <e>Obama</e> ‰ÑÈ <e>Romney</e> ‰ÏÓPedro #...     2
2397   @DMichael_ It leaves out other black immigran...     0
2398   @BarackObama <e>Romney</e>. <e>Obama</e> need...    -1
2399   <e>Barack Obama</e> and Candy Crowley vs. <e>...     2
2400   Rae Sky  My company's stock hit a 52-week hig...     0

[2401 rows x 2 columns]

In [15]:
precision = [i for i in range(3)]
recall = [i for i in range(3)]
f1score = [i for i in range(3)]
print("Testing accuracy")
print("Overall Acurracy : ",12)
lbl = ['positive', 'negative', 'nuetral']
for i in range(3):
    print("Precision of %s class: %f" %(lbl[i], precision[i]))
    print("Recall of %s class: %f" %(lbl[i],recall[i]))
    print("F1-Score of %s class: %f" %(lbl[i],f1score[i]))
    print()

Testing accuracy
Overall Acurracy :  12
Precision of positive class: 0.000000
Recall of positive class: 0.000000
F1-Score of positive class: 0.000000

Precision of negative class: 1.000000
Recall of negative class: 1.000000
F1-Score of negative class: 1.000000

Precision of nuetral class: 2.000000
Recall of nuetral class: 2.000000
F1-Score of nuetral class: 2.000000



In [ ]:
print("Precision of %s class: %f" %(i+1,det_acc_score[i]))